fruits = list()

print("Fruits queue -> ", fruits)
fruits.append('m')
print("Fruits queue -> ", fruits)
fruits.append('a')
print("Fruits queue -> ", fruits)
fruits.append('n')
print("Fruits queue -> ", fruits)
fruits.append('g')
print("Fruits queue -> ", fruits)
fruits.append('o')

print("Fruits queue -> ", fruits)

print(fruits.pop(0))
print("Fruits queue -> ", fruits)
print(fruits.pop(0))
print("Fruits queue -> ", fruits)
print(fruits.pop(0))
print("Fruits queue -> ", fruits)